# Generated by Django 5.2.17 on 2026-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_user_profile_photo_emailotprequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
