# Generated by Django 5.2.17 on 2026-09-14 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedaddress',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedaddress',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RecurringRideSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('days_of_week', models.JSONField(default=list, help_text='List of DayOfWeek integers, e.g. [0, 2, 4]')),
                ('time_of_day', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.savedaddress')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_ride_schedules', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.savedaddress')),
            ],
            options={
                'ordering': ['time_of_day'],
            },
        ),
    ]
