# Generated by Django 5.2.17 on 2026-09-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotprequest',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Sign-up verification'), ('password_reset', 'Password reset')], default='signup', max_length=20),
        ),
    ]
