# Generated by Django 5.2.17 on 2026-09-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Rider'), ('admin', 'Admin'), ('support', 'Admin (support)')], default='passenger', max_length=20),
        ),
    ]
