# Generated by Django 5.2.17 on 2026-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='security_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicezone',
            name='security_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
