# Generated by Django 5.2.17 on 2026-10-07 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0002_pickuppoint_sponsor_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "aliases",
                    models.CharField(
                        blank=True,
                        help_text="Other names people use, separated by commas. e.g. 'Citadel, Citadel Hostel Annex'",
                        max_length=300,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Shown under the name, e.g. 'Nyankpala campus'",
                        max_length=150,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "popularity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher shows first when several places match.",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for a place that belongs to every zone.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="zones.servicezone",
                    ),
                ),
            ],
            options={
                "ordering": ["-popularity", "name"],
                "indexes": [
                    models.Index(
                        fields=["zone", "is_active"],
                        name="zones_place_zone_id_677b73_idx",
                    )
                ],
            },
        ),
    ]
