# Generated by Django 5.2.17 on 2026-09-10 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence_number', models.CharField(max_length=50)),
                ('licence_expiry', models.DateField(blank=True, null=True)),
                ('licence_document', models.URLField(blank=True, help_text='Cloudinary URL')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('quality_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('is_online', models.BooleanField(default=False)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('current_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='zones.servicezone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('yellow_yellow', 'Yellow-Yellow / Tricycle')], default='yellow_yellow', max_length=30)),
                ('registration_document', models.URLField(blank=True, help_text='Cloudinary URL')),
                ('photo', models.URLField(blank=True, help_text='Cloudinary URL')),
                ('active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['verification_status', 'is_online'], name='drivers_dri_verific_046806_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['current_zone', 'is_online'], name='drivers_dri_current_174c1b_idx'),
        ),
    ]
