# Generated by Django 5.2.17 on 2026-09-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='accepts_deliveries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='accessibility_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='has_luggage_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='offers_quiet_ride',
            field=models.BooleanField(default=False),
        ),
    ]
