# Generated by Django 5.2.17 on 2026-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_accepts_deliveries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Not stated'), ('female', 'Female'), ('male', 'Male')], default='', max_length=10),
        ),
    ]
