# Generated by Django 5.2.17 on 2026-09-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='payout_phone',
            field=models.CharField(blank=True, help_text='Where payouts are sent. Blank falls back to the account phone.', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='payout_provider',
            field=models.CharField(choices=[('momo', 'MTN MoMo'), ('hubtel', 'Hubtel')], default='momo', max_length=10),
        ),
    ]
