# Generated by Django 5.2.17 on 2026-10-01 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_payout_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderPassPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['duration_days', 'price'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='ghana_card_document',
            field=models.URLField(blank=True, help_text='Cloudinary URL'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ghana_card_number',
            field=models.CharField(blank=True, default='', help_text='Format GHA-123456789-0', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='transport_union',
            field=models.CharField(blank=True, default='', help_text='e.g. National Union of Tricycle Operators, Tamale branch', max_length=120),
        ),
        migrations.AddField(
            model_name='driver',
            name='union_card_document',
            field=models.URLField(blank=True, help_text='Cloudinary URL'),
        ),
        migrations.AddField(
            model_name='driver',
            name='union_membership_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='roadworthy_certificate',
            field=models.URLField(blank=True, help_text='Cloudinary URL'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='roadworthy_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licence_number',
            field=models.CharField(help_text="DVLA commercial rider's licence number", max_length=50),
        ),
        migrations.CreateModel(
            name='RiderPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('trial', 'Free trial'), ('momo', 'Mobile Money'), ('cash', 'Paid to ops (cash)'), ('grant', 'Granted by ops')], max_length=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='drivers.driver')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Admin who recorded a cash payment or grant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='drivers.riderpassplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'status', 'expires_at'], name='drivers_rid_driver__bc906d_idx')],
            },
        ),
    ]
