# Generated by Django 5.2.17 on 2026-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_rider_passes_and_li2519_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="ghana_card_document",
            field=models.URLField(blank=True, help_text="File URL"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="licence_document",
            field=models.URLField(blank=True, help_text="File URL"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="union_card_document",
            field=models.URLField(blank=True, help_text="File URL"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="photo",
            field=models.URLField(blank=True, help_text="File URL"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="registration_document",
            field=models.URLField(blank=True, help_text="File URL"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="roadworthy_certificate",
            field=models.URLField(blank=True, help_text="File URL"),
        ),
    ]
