# Generated by Django 5.2.17 on 2026-09-23 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
        ('organizations', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farequote',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='farequote',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='farequote',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='bundles.passengerbundle'),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='trip',
            name='kind',
            field=models.CharField(choices=[('ride', 'Ride'), ('delivery', 'Delivery')], default='ride', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='trip',
            name='package_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('organization', 'Billed to organization'), ('bundle', 'Prepaid bundle')], default='cash', max_length=15),
        ),
        migrations.AddField(
            model_name='trip',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trip',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RidePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiet_ride', models.BooleanField(default=False)),
                ('needs_luggage_space', models.BooleanField(default=False)),
                ('needs_accessibility_help', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
