# Generated by Django 5.2.17 on 2026-09-24 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_accepts_deliveries_and_more'),
        ('trips', '0002_farequote_discount_farequote_discount_reason_and_more'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='seats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RidePool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='drivers.driver')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='zones.servicezone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.ridepool'),
        ),
    ]
