# Generated by Django 5.2.17 on 2026-09-25 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_passengerbundle_short_expiry_acknowledged_and_more'),
        ('drivers', '0003_driver_gender'),
        ('organizations', '0002_organization_prepaid_balance_balanceentry_and_more'),
        ('trips', '0004_prd_alignment'),
        ('zones', '0002_pickuppoint_sponsor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'completed_at'], name='trips_trip_status_b846c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tripevent',
            index=models.Index(fields=['event_type', 'created_at'], name='trips_tripe_event_t_ad9746_idx'),
        ),
    ]
