# Generated by Django 5.2.17 on 2026-09-27 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_trips_trip_status_b846c1_idx_and_more'),
        ('zones', '0002_pickuppoint_sponsor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetail',
            name='delivery_subtype',
            field=models.CharField(choices=[('parcel', 'Parcel (sender to recipient)'), ('errand', 'Errand (buy/collect a task)'), ('vendor_order', 'Vendor order')], default='parcel', max_length=15),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='spend_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='package_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='zones.servicezone')),
            ],
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trips.vendor'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='trips_vendo_name_ce1b47_idx'),
        ),
    ]
