# Generated by Django 5.2.17 on 2026-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_trips_trip_status_b846c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('hubtel', 'Hubtel'), ('organization', 'Billed to organization'), ('voucher', 'Organization voucher'), ('bundle', 'Prepaid bundle')], default='cash', max_length=15),
        ),
    ]
