# Generated by Django 5.2.17 on 2026-09-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_alter_trip_payment_method"),
        ("trips", "0006_deliverydetail_delivery_subtype_and_more"),
    ]

    operations = []
