# Generated by Django 5.2.17 on 2026-09-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_merge_20260927_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetail',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
