# Generated by Django 5.2.17 on 2026-09-28 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_delivery_sender_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCourier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='trip',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('system', 'System'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('matching', 'Matching'), ('matched', 'Matched'), ('driver_arriving', 'Driver Arriving'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_drivers_found', 'No Drivers Found'), ('awaiting_assignment', 'Being arranged')], default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='external_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='trips.externalcourier'),
        ),
    ]
