# Generated by Django 5.2.17 on 2026-09-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_admin_delivery_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='preference_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('awaiting_rider', "Waiting for passenger's decision"), ('keep_waiting', 'Rider chose to keep waiting'), ('relaxed', 'Rider accepted any driver')], default='', max_length=15),
        ),
    ]
