# Generated by Django 5.2.17 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_awaiting_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('passenger', 'Passenger'), ('driver', 'Rider'), ('system', 'System'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='preference_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('awaiting_passenger', "Waiting for passenger's decision"), ('keep_waiting', 'Passenger chose to keep waiting'), ('relaxed', 'Passenger accepted any rider')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('matching', 'Matching'), ('matched', 'Matched'), ('driver_arriving', 'Rider Arriving'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_drivers_found', 'No Riders Found'), ('awaiting_assignment', 'Being arranged')], default='requested', max_length=20),
        ),
    ]
