# Generated by Django 5.2.17 on 2026-09-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payout_commission_rate_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('organization', 'Billed to organization'), ('bundle', 'Prepaid bundle')], max_length=15),
        ),
    ]
