# Generated by Django 5.2.17 on 2026-09-24 05:31

from django.db import migrations, models


def backfill(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    Payment.objects.filter(method="momo").update(funding_source="momo")
    Payment.objects.filter(method="organization").update(funding_source="organization_account")
    Payment.objects.filter(method="bundle").update(funding_source="ride_bundle")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_confirmed_by_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='funding_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('organization_account', 'Organization account'), ('organization_voucher', 'Organization voucher'), ('ride_bundle', 'Ride bundle')], default='cash', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('organization', 'Billed to organization'), ('voucher', 'Organization voucher'), ('bundle', 'Prepaid bundle')], max_length=15),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
