# Generated by Django 5.2.17 on 2026-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_funding_source_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='funding_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('hubtel', 'Hubtel'), ('organization_account', 'Organization account'), ('organization_voucher', 'Organization voucher'), ('ride_bundle', 'Ride bundle')], default='cash', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('hubtel', 'Hubtel'), ('organization', 'Billed to organization'), ('voucher', 'Organization voucher'), ('bundle', 'Prepaid bundle')], max_length=15),
        ),
    ]
