# Generated by Django 5.2.17 on 2026-09-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_funding_source_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='provider',
            field=models.CharField(blank=True, help_text='momo or hubtel — set when disbursed', max_length=10),
        ),
    ]
