# Generated by Django 5.2.17 on 2026-09-24 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('zones', '0002_pickuppoint_sponsor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('image_url', models.URLField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('sponsor_name', models.CharField(max_length=150)),
                ('active_from', models.DateTimeField()),
                ('active_to', models.DateTimeField()),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='partners.partner')),
                ('zone', models.ForeignKey(blank=True, help_text='Blank = every zone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='zones.servicezone')),
            ],
            options={
                'ordering': ['-active_from'],
            },
        ),
    ]
