# Generated by Django 5.2.17 on 2026-09-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_sponsoredplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='offer_text',
            field=models.CharField(blank=True, help_text='Shown to passengers, e.g. "10% off with code WAAKYE10"', max_length=200),
        ),
    ]
