# Generated by Django 5.2.17 on 2026-09-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        ('trips', '0004_prd_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='trips.trip'),
        ),
    ]
