"""
Django settings for wolbirides project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback value here is only ever used when DJANGO_SECRET_KEY isn't
# set (i.e. local dev) — every real deployment must set it via env var.
# Previously this was hardcoded with no env override at all, meaning the
# same well-known "insecure" key would have shipped to every environment
# including production if this file were ever deployed as-is.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-7u)c&ly&3p2$k1dgy81^myx)5b7)4^majz4_62-)p+)6giz9bf',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() in ('1', 'true', 'yes')

# Comma-separated list, e.g. "api.wolbirides.com,wolbirides.onrender.com".
# Empty is fine (and safe) for local dev with DEBUG=True — Django allows
# localhost/127.0.0.1 automatically in that mode regardless of this list.
if not DEBUG and SECRET_KEY.startswith('django-insecure'):
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY before running with DJANGO_DEBUG=False.')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG:
    # Development only: a phone on a hotspot or Wi-Fi reaches this computer by whatever address the network
    # gave it, and that changes. Django's default for DEBUG is localhost only, so a fixed list here made every
    # phone request fail with "Invalid HTTP_HOST" (which the apps then reported as a wrong password).
    # Production (DEBUG=False) still uses exactly the list above; with an empty list Django rejects every request.
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'corsheaders',
    'core',
    'accounts',
    'zones',
    'drivers',
    'trips',
    'payments',
    'incidents',
    'support',
    'adminapi',
    'safety',
    'organizations',
    'bundles',
    'partners',
    'rest_framework_simplejwt.token_blacklist',  # lets a password reset sign out other devices
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wolbirides.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wolbirides.wsgi.application'
ASGI_APPLICATION = 'wolbirides.asgi.application'

REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}

# --- Celery (dispatch-offer timeout cascade, see trips/tasks.py) ---
from celery.schedules import crontab  # noqa: E402

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# WR-13: recurring-ride reminder sweep. Requires `celery -A wolbirides beat`
# running alongside the worker in production — a 5-minute interval against
# a 15-minute reminder window (accounts/tasks.py) gives comfortable overlap
# without needing sub-minute precision.
CELERY_BEAT_SCHEDULE = {
    'flush-expired-tokens': {
        'task': 'core.tasks.flush_expired_tokens',
        'schedule': crontab(hour=3, minute=30),
    },
    # MoMo payouts accepted by MTN but not yet final.
    'check-processing-payouts': {
        'task': 'payments.tasks.check_processing_payouts',
        'schedule': 300.0,
    },
    # WR-21: invoices for last month, 1st of each month 01:00 UTC.
    'generate-monthly-invoices': {
        'task': 'organizations.tasks.generate_monthly_invoices',
        'schedule': crontab(hour=1, minute=0, day_of_month=1),
    },
    # WR-22: retire expired bundles hourly.
    'expire-bundles': {
        'task': 'bundles.tasks.expire_bundles',
        'schedule': 3600.0,
    },
    # WR-18: overdue-trip check-ins and escalation of unanswered ones.
    'run-safety-checks': {
        'task': 'safety.tasks.run_safety_checks',
        'schedule': 60.0,
    },
    'send-recurring-ride-reminders': {
        'task': 'accounts.tasks.send_recurring_ride_reminders',
        'schedule': 300.0,
    },
    # WR-14: Monday 00:05 UTC — generates payouts for the week that just
    # ended (Mon-Sun). Generation only; disbursement requires admin
    # approval during the pilot (see PayoutBatchApproveView).
    'run-weekly-payout-batch': {
        'task': 'payments.tasks.run_weekly_payout_batch',
        'schedule': crontab(hour=0, minute=5, day_of_week=1),
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        # Coarse per-IP backstop applied to every AllowAny endpoint by
        # default (see DEFAULT_THROTTLE_CLASSES above) — stops one source
        # rapidly enumerating many different targets. The per-target
        # throttles below (core/throttling.py) are the primary defense
        # against harassing a single phone/email and are applied per-view.
        'anon': '30/hour',
        # Per signed-in user, for actions that cost money or can spam (DRF ScopedRateThrottle + throttle_scope).
        'assistant': '30/hour',
        'trip_request': '30/hour',
        'trip_share': '20/hour',
        'voucher_redeem': '10/hour',
        'support_ticket': '10/hour',
        'momo_initiate': '10/hour',
        'hubtel_initiate': '10/hour',
        'otp_request_phone': '3/10min',
        'otp_request_email': '3/10min',
        'login_email': '10/10min',
        'signup_email': '5/10min',
    },
}

# Long-lived refresh token = "stay signed in until you sign out" (WR UX
# overhaul, item 1). Access tokens stay short-lived; the frontend silently
# calls /api/auth/token/refresh on a 401 rather than forcing a re-login.
from datetime import timedelta  # noqa: E402


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    # Each refresh returns a NEW refresh token and blacklists the old one, so a stolen
    # refresh token stops working as soon as the real app refreshes (at most an hour).
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Dev fallback: with no real SMTP configured, emails print to the runserver
# console (same "log instead of send" pattern as AFRICASTALKING_USERNAME
# below for SMS) so signup works end-to-end without a mail provider.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@wolbirides.local')

# AI Assistant (WR UX overhaul, item 3) — server-side call to the Anthropic
# API so the key never reaches the browser. With no key set, the assistant
# endpoint returns a clear "not configured" error instead of failing oddly.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

# WolbiRides is API-only for passenger/driver clients; admin dashboard is a
# separate React app, hence permissive CORS scoped by env var in production.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:5174,http://localhost:5175,http://localhost:5176'
).split(',')

# --- Third-party integrations (reused from other Wolbi platforms) ---
AFRICASTALKING_USERNAME = os.environ.get('AFRICASTALKING_USERNAME', '')
AFRICASTALKING_API_KEY = os.environ.get('AFRICASTALKING_API_KEY', '')
# MTN MoMo (payments/momo.py). Collections charge passengers; Disbursements pay
# drivers. Each needs its own subscription key + API user + API key from the
# MTN developer portal. Leave blank for dev mode (no calls to MTN).
MOMO_BASE_URL = os.environ.get('MOMO_BASE_URL', 'https://sandbox.momodeveloper.mtn.com')
MOMO_TARGET_ENVIRONMENT = os.environ.get('MOMO_TARGET_ENVIRONMENT', 'sandbox')  # production: e.g. 'mtnghana'
MOMO_CURRENCY = os.environ.get('MOMO_CURRENCY', 'GHS')
MOMO_CALLBACK_URL = os.environ.get('MOMO_CALLBACK_URL', '')  # https://<api-host>/api/payments/momo/webhook
MOMO_COLLECTION_SUBSCRIPTION_KEY = os.environ.get('MOMO_COLLECTION_SUBSCRIPTION_KEY', '')
MOMO_COLLECTION_API_USER = os.environ.get('MOMO_COLLECTION_API_USER', '')
MOMO_COLLECTION_API_KEY = os.environ.get('MOMO_COLLECTION_API_KEY', '')
MOMO_DISBURSEMENT_SUBSCRIPTION_KEY = os.environ.get('MOMO_DISBURSEMENT_SUBSCRIPTION_KEY', '')
MOMO_DISBURSEMENT_API_USER = os.environ.get('MOMO_DISBURSEMENT_API_USER', '')
MOMO_DISBURSEMENT_API_KEY = os.environ.get('MOMO_DISBURSEMENT_API_KEY', '')
# Dev only: with no Collections credentials, a pending MoMo payment is marked
# successful on its first status check so the whole flow can be clicked through.
MOMO_DEV_AUTO_APPROVE = os.environ.get('MOMO_DEV_AUTO_APPROVE', 'True').lower() in ('1', 'true', 'yes')

# Hubtel: unverified against Hubtel's real API — see payments/hubtel.py's module docstring.
HUBTEL_BASE_URL = os.environ.get('HUBTEL_BASE_URL', 'https://rmp.hubtel.com')
HUBTEL_CLIENT_ID = os.environ.get('HUBTEL_CLIENT_ID', '')
HUBTEL_CLIENT_SECRET = os.environ.get('HUBTEL_CLIENT_SECRET', '')
HUBTEL_MERCHANT_ACCOUNT_NUMBER = os.environ.get('HUBTEL_MERCHANT_ACCOUNT_NUMBER', '')
HUBTEL_CALLBACK_URL = os.environ.get('HUBTEL_CALLBACK_URL', '')  # https://<api-host>/api/payments/hubtel/webhook
# WR-26: which delivery types go to the ops queue for a person to assign, instead of straight to
# nearby drivers. Parcels dispatch automatically and only fall back to the queue if no driver takes
# them. Errands and vendor orders involve a cash float and a third party, so a person checks first.
DELIVERY_ADMIN_FIRST_SUBTYPES = [
    s.strip() for s in os.environ.get('DELIVERY_ADMIN_FIRST_SUBTYPES', 'errand,vendor_order').split(',') if s.strip()
]
# WR-26: how long a driver ops directly offered a delivery to has to accept or decline before
# it returns to the queue. Deliberately longer than organic dispatch's snap-decision race
# (trips.services.DISPATCH_OFFER_TIMEOUT_SECONDS) since ops picked this one driver on purpose,
# rather than racing the nearest few — the point is giving them time to actually notice, not speed.
ADMIN_OFFER_TIMEOUT_SECONDS = int(os.environ.get('ADMIN_OFFER_TIMEOUT_SECONDS', '180'))
HUBTEL_DEV_AUTO_APPROVE = os.environ.get('HUBTEL_DEV_AUTO_APPROVE', 'True').lower() in ('1', 'true', 'yes')

# WR-14: driver commission rate for automated weekly payouts. Kept as a
# single global env-driven value for now (0.00 = founding-driver 0%
# commission period per WR-07.4) rather than a per-zone/per-driver admin
# UI — matches the "start simple, adjust once real data exists" approach
# the rest of the platform's pricing logic already follows.
DEFAULT_DRIVER_COMMISSION_RATE = float(os.environ.get('DEFAULT_DRIVER_COMMISSION_RATE', '0.0'))

CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')
if CLOUDINARY_URL:
    # The cloudinary SDK can auto-parse CLOUDINARY_URL from the process
    # environment on its own, but configuring it explicitly here means it
    # works the same way regardless of import order or whether something
    # else already imported cloudinary before Django settings ran.
    import cloudinary as _cloudinary
    _cloudinary.config(cloudinary_url=CLOUDINARY_URL, secure=True)


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASE_URL was previously documented in .env.example but never actually
# read anywhere — setting it in production silently did nothing and SQLite
# kept being used regardless. Wired up for real here: set DATABASE_URL to
# switch to Postgres (or anything dj-database-url supports); leave it unset
# for local dev and SQLite is used automatically.
_database_url = os.environ.get('DATABASE_URL', '')
if _database_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.parse(_database_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic target; served by WhiteNoise


# Email
# https://docs.djangoproject.com/en/5.2/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# WR-18: shown to users after they press SOS. 112 is Ghana's unified
# emergency number; override per deployment if needed.
SAFETY_EMERGENCY_NUMBER = os.environ.get("SAFETY_EMERGENCY_NUMBER", "112")

# WR-18 trip sharing + check-ins
PASSENGER_WEB_URL = os.environ.get("PASSENGER_WEB_URL", "http://localhost:5174")
SAFETY_EXPECTED_SPEED_KMH = float(os.environ.get("SAFETY_EXPECTED_SPEED_KMH", "15"))
SAFETY_OVERDUE_FACTOR = float(os.environ.get("SAFETY_OVERDUE_FACTOR", "2"))
SAFETY_OVERDUE_GRACE_MINUTES = float(os.environ.get("SAFETY_OVERDUE_GRACE_MINUTES", "10"))
SAFETY_CHECKIN_RESPONSE_MINUTES = float(os.environ.get("SAFETY_CHECKIN_RESPONSE_MINUTES", "3"))

# WR-19/20 dispatch ordering: drivers within this many km of the nearest
# candidate are treated as equally close, then ordered by preference match
# and by who has waited longest for a trip.
FAIR_QUEUE_BAND_KM = float(os.environ.get("FAIR_QUEUE_BAND_KM", "0.5"))
# WR-20 fairness floor: share of dispatches (PRD: 10-20%) that go to the in-band
# driver with the fewest trips in the last 7 days instead of the nearest.
FAIR_QUEUE_SHARE = float(os.environ.get("FAIR_QUEUE_SHARE", "0.15"))

# WR-22: bundles expiring sooner than a full academic term need explicit acknowledgement.
BUNDLE_MIN_TERM_DAYS = int(os.environ.get("BUNDLE_MIN_TERM_DAYS", "120"))

# WR-23/25 WolbiDeliver surcharges, added on top of the distance fare.
# Parcels are priced by package size (bigger item, more effort/risk to carry).
DELIVERY_SURCHARGE_BY_SIZE = {
    "small": os.environ.get("DELIVERY_SURCHARGE_SMALL", "3.00"),
    "medium": os.environ.get("DELIVERY_SURCHARGE_MEDIUM", "5.00"),
    "large": os.environ.get("DELIVERY_SURCHARGE_LARGE", "8.00"),
}
# Errands and vendor orders have no package_size (the courier is buying/collecting on the
# requester's behalf, not carrying a pre-packed item), so they take one flat task fee instead.
DELIVERY_TASK_SURCHARGE = os.environ.get("DELIVERY_TASK_SURCHARGE", "4.00")

# Behind nginx/a load balancer terminating TLS.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# WR-17 shared rides. PRD cap: 2 passengers per yellow-yellow. Pricing: base fare
# shared, each passenger pays their own distance charge, never above their solo fare.
POOL_MAX_PASSENGERS = int(os.environ.get("POOL_MAX_PASSENGERS", os.environ.get("POOL_MAX_RIDERS", "2")))  # POOL_MAX_RIDERS: old name
POOL_PICKUP_RADIUS_KM = float(os.environ.get("POOL_PICKUP_RADIUS_KM", "0.8"))
POOL_DESTINATION_RADIUS_KM = float(os.environ.get("POOL_DESTINATION_RADIUS_KM", "1.5"))
POOL_JOIN_WINDOW_MINUTES = float(os.environ.get("POOL_JOIN_WINDOW_MINUTES", "5"))


# --- Production HTTPS hardening (only when DJANGO_DEBUG=False; local dev is unaffected) ---
# TLS is expected to terminate at your host or load balancer; nginx forwards the original
# X-Forwarded-Proto (see frontend nginx.conf), which SECURE_PROXY_SSL_HEADER above trusts.
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True').lower() in ('1', 'true', 'yes')
    # Start at 30 days; raise to 31536000 (1 year) once HTTPS has been solid for a while.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '2592000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() in ('1', 'true', 'yes')
    # Browser preload list: effectively permanent. Enable only with 1-year HSTS on every subdomain.
    SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_SECURE_HSTS_PRELOAD', 'False').lower() in ('1', 'true', 'yes')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# --- Django admin location ---
# Not at the well-known /admin/ in production: set DJANGO_ADMIN_PATH to something only your
# team knows (e.g. "ops-7f3k2/"). Local development keeps /admin/ unless you set it.
ADMIN_PATH = os.environ.get('DJANGO_ADMIN_PATH', '' if not DEBUG else 'admin').strip().strip('/')
if not ADMIN_PATH:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured('Set DJANGO_ADMIN_PATH (a private path for Django admin) before running with DJANGO_DEBUG=False.')
if ADMIN_PATH in ('admin', 'api', 'ws', 'static'):
    if not DEBUG:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured('DJANGO_ADMIN_PATH must not be a well-known path like "admin" in production.')
ADMIN_PATH += '/'
