# Generated by Django 5.2.17 on 2026-09-23 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('ride_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_fare_per_ride', models.DecimalField(decimal_places=2, help_text="Rides costing more than this can't use the bundle", max_digits=8)),
                ('valid_days', models.PositiveIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rides_total', models.PositiveIntegerField()),
                ('rides_remaining', models.PositiveIntegerField()),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_fare_per_ride', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('active', 'Active'), ('exhausted', 'Used up'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='bundles.bundleplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('used', 'Used'), ('released', 'Released')], default='reserved', max_length=10)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_redemption', to='trips.trip')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='bundles.passengerbundle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
