# Generated by Django 5.2.17 on 2026-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerbundle',
            name='short_expiry_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bundleplan',
            name='valid_days',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
