# Generated by Django 5.2.17 on 2026-09-12 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('trip', 'Trip'), ('driver', 'Driver'), ('incident', 'Incident'), ('support', 'Support'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read'], name='core_notifi_user_id_4a178e_idx')],
            },
        ),
    ]
