# Generated by Django 5.2.17 on 2026-09-16 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('trip', 'Trip'), ('driver', 'Driver'), ('incident', 'Incident'), ('support', 'Support'), ('system', 'System'), ('payout', 'Payout'), ('recurring_reminder', 'Recurring ride reminder')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('trip', 'Trip'), ('driver', 'Driver'), ('incident', 'Incident'), ('support', 'Support'), ('system', 'System'), ('payout', 'Payout'), ('recurring_reminder', 'Recurring ride reminder')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='one_preference_per_user_category')],
            },
        ),
    ]
