# Generated by Django 5.2.17 on 2026-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('trip', 'Trip'), ('driver', 'Rider'), ('incident', 'Incident'), ('support', 'Support'), ('system', 'System'), ('payout', 'Payout'), ('recurring_reminder', 'Recurring ride reminder')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('trip', 'Trip'), ('driver', 'Rider'), ('incident', 'Incident'), ('support', 'Support'), ('system', 'System'), ('payout', 'Payout'), ('recurring_reminder', 'Recurring ride reminder')], max_length=20),
        ),
    ]
